/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as LandingTermsOfServiceRouteImport } from './routes/_landing/terms-of-service'
import { Route as LandingPrivacyPolicyRouteImport } from './routes/_landing/privacy-policy'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppConfigRouteImport } from './routes/_app/config'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as AppIntegrationsIndexRouteImport } from './routes/_app/integrations/index'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSummariesIdRouteImport } from './routes/_app/summaries.$id'
import { Route as AppSettingsSettingsRouteImport } from './routes/_app/settings/_settings'
import { Route as AppProjectsAddRouteImport } from './routes/_app/projects/add'
import { Route as ApiInstallationsGithubNewRouteImport } from './routes/api/installations/github/new'
import { Route as ApiInstallationsGithubCallbackRouteImport } from './routes/api/installations/github/callback'
import { Route as AppSettingsSettingsSecurityRouteImport } from './routes/_app/settings/_settings.security'
import { Route as AppSettingsSettingsBillingRouteImport } from './routes/_app/settings/_settings.billing'
import { Route as AppSettingsSettingsAccountRouteImport } from './routes/_app/settings/_settings.account'

const AppSettingsRouteImport = createFileRoute('/_app/settings')()

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingTermsOfServiceRoute = LandingTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyPolicyRoute = LandingPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LandingRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSummariesIdRoute = AppSummariesIdRouteImport.update({
  id: '/summaries/$id',
  path: '/summaries/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSettingsRoute = AppSettingsSettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsAddRoute = AppProjectsAddRouteImport.update({
  id: '/projects/add',
  path: '/projects/add',
  getParentRoute: () => AppRoute,
} as any)
const ApiInstallationsGithubNewRoute =
  ApiInstallationsGithubNewRouteImport.update({
    id: '/api/installations/github/new',
    path: '/api/installations/github/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInstallationsGithubCallbackRoute =
  ApiInstallationsGithubCallbackRouteImport.update({
    id: '/api/installations/github/callback',
    path: '/api/installations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsSettingsSecurityRoute =
  AppSettingsSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AppSettingsSettingsRoute,
  } as any)
const AppSettingsSettingsBillingRoute =
  AppSettingsSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppSettingsSettingsRoute,
  } as any)
const AppSettingsSettingsAccountRoute =
  AppSettingsSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AppSettingsSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppAppRoute
  '/config': typeof AppConfigRoute
  '/sign-in': typeof AuthSignInRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/terms-of-service': typeof LandingTermsOfServiceRoute
  '/api/inngest': typeof ApiInngestRoute
  '/': typeof LandingIndexRoute
  '/projects/add': typeof AppProjectsAddRoute
  '/settings': typeof AppSettingsSettingsRouteWithChildren
  '/summaries/$id': typeof AppSummariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/settings/account': typeof AppSettingsSettingsAccountRoute
  '/settings/billing': typeof AppSettingsSettingsBillingRoute
  '/settings/security': typeof AppSettingsSettingsSecurityRoute
  '/api/installations/github/callback': typeof ApiInstallationsGithubCallbackRoute
  '/api/installations/github/new': typeof ApiInstallationsGithubNewRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppAppRoute
  '/config': typeof AppConfigRoute
  '/sign-in': typeof AuthSignInRoute
  '/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/terms-of-service': typeof LandingTermsOfServiceRoute
  '/api/inngest': typeof ApiInngestRoute
  '/': typeof LandingIndexRoute
  '/projects/add': typeof AppProjectsAddRoute
  '/settings': typeof AppSettingsSettingsRouteWithChildren
  '/summaries/$id': typeof AppSummariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/integrations': typeof AppIntegrationsIndexRoute
  '/settings/account': typeof AppSettingsSettingsAccountRoute
  '/settings/billing': typeof AppSettingsSettingsBillingRoute
  '/settings/security': typeof AppSettingsSettingsSecurityRoute
  '/api/installations/github/callback': typeof ApiInstallationsGithubCallbackRoute
  '/api/installations/github/new': typeof ApiInstallationsGithubNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_app/app': typeof AppAppRoute
  '/_app/config': typeof AppConfigRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_landing/privacy-policy': typeof LandingPrivacyPolicyRoute
  '/_landing/terms-of-service': typeof LandingTermsOfServiceRoute
  '/api/inngest': typeof ApiInngestRoute
  '/_landing/': typeof LandingIndexRoute
  '/_app/projects/add': typeof AppProjectsAddRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/settings/_settings': typeof AppSettingsSettingsRouteWithChildren
  '/_app/summaries/$id': typeof AppSummariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/_app/integrations/': typeof AppIntegrationsIndexRoute
  '/_app/settings/_settings/account': typeof AppSettingsSettingsAccountRoute
  '/_app/settings/_settings/billing': typeof AppSettingsSettingsBillingRoute
  '/_app/settings/_settings/security': typeof AppSettingsSettingsSecurityRoute
  '/api/installations/github/callback': typeof ApiInstallationsGithubCallbackRoute
  '/api/installations/github/new': typeof ApiInstallationsGithubNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/config'
    | '/sign-in'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/inngest'
    | '/'
    | '/projects/add'
    | '/settings'
    | '/summaries/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/integrations'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/security'
    | '/api/installations/github/callback'
    | '/api/installations/github/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/config'
    | '/sign-in'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/inngest'
    | '/'
    | '/projects/add'
    | '/settings'
    | '/summaries/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/integrations'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/security'
    | '/api/installations/github/callback'
    | '/api/installations/github/new'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_landing'
    | '/_app/app'
    | '/_app/config'
    | '/_auth/sign-in'
    | '/_landing/privacy-policy'
    | '/_landing/terms-of-service'
    | '/api/inngest'
    | '/_landing/'
    | '/_app/projects/add'
    | '/_app/settings'
    | '/_app/settings/_settings'
    | '/_app/summaries/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/_app/integrations/'
    | '/_app/settings/_settings/account'
    | '/_app/settings/_settings/billing'
    | '/_app/settings/_settings/security'
    | '/api/installations/github/callback'
    | '/api/installations/github/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiInstallationsGithubCallbackRoute: typeof ApiInstallationsGithubCallbackRoute
  ApiInstallationsGithubNewRoute: typeof ApiInstallationsGithubNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/terms-of-service': {
      id: '/_landing/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LandingTermsOfServiceRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy-policy': {
      id: '/_landing/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LandingPrivacyPolicyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/': {
      id: '/_app/integrations/'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/summaries/$id': {
      id: '/_app/summaries/$id'
      path: '/summaries/$id'
      fullPath: '/summaries/$id'
      preLoaderRoute: typeof AppSummariesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/_settings': {
      id: '/_app/settings/_settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsSettingsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/projects/add': {
      id: '/_app/projects/add'
      path: '/projects/add'
      fullPath: '/projects/add'
      preLoaderRoute: typeof AppProjectsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/installations/github/new': {
      id: '/api/installations/github/new'
      path: '/api/installations/github/new'
      fullPath: '/api/installations/github/new'
      preLoaderRoute: typeof ApiInstallationsGithubNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/installations/github/callback': {
      id: '/api/installations/github/callback'
      path: '/api/installations/github/callback'
      fullPath: '/api/installations/github/callback'
      preLoaderRoute: typeof ApiInstallationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/_settings/security': {
      id: '/_app/settings/_settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsSettingsRoute
    }
    '/_app/settings/_settings/billing': {
      id: '/_app/settings/_settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsSettingsBillingRouteImport
      parentRoute: typeof AppSettingsSettingsRoute
    }
    '/_app/settings/_settings/account': {
      id: '/_app/settings/_settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsSettingsAccountRouteImport
      parentRoute: typeof AppSettingsSettingsRoute
    }
  }
}

interface AppSettingsSettingsRouteChildren {
  AppSettingsSettingsAccountRoute: typeof AppSettingsSettingsAccountRoute
  AppSettingsSettingsBillingRoute: typeof AppSettingsSettingsBillingRoute
  AppSettingsSettingsSecurityRoute: typeof AppSettingsSettingsSecurityRoute
}

const AppSettingsSettingsRouteChildren: AppSettingsSettingsRouteChildren = {
  AppSettingsSettingsAccountRoute: AppSettingsSettingsAccountRoute,
  AppSettingsSettingsBillingRoute: AppSettingsSettingsBillingRoute,
  AppSettingsSettingsSecurityRoute: AppSettingsSettingsSecurityRoute,
}

const AppSettingsSettingsRouteWithChildren =
  AppSettingsSettingsRoute._addFileChildren(AppSettingsSettingsRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsSettingsRoute: typeof AppSettingsSettingsRouteWithChildren
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsSettingsRoute: AppSettingsSettingsRouteWithChildren,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppConfigRoute: typeof AppConfigRoute
  AppProjectsAddRoute: typeof AppProjectsAddRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSummariesIdRoute: typeof AppSummariesIdRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppConfigRoute: AppConfigRoute,
  AppProjectsAddRoute: AppProjectsAddRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSummariesIdRoute: AppSummariesIdRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LandingRouteChildren {
  LandingPrivacyPolicyRoute: typeof LandingPrivacyPolicyRoute
  LandingTermsOfServiceRoute: typeof LandingTermsOfServiceRoute
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingPrivacyPolicyRoute: LandingPrivacyPolicyRoute,
  LandingTermsOfServiceRoute: LandingTermsOfServiceRoute,
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiInstallationsGithubCallbackRoute: ApiInstallationsGithubCallbackRoute,
  ApiInstallationsGithubNewRoute: ApiInstallationsGithubNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
