/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as ApiTestRouteImport } from './routes/api/test'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSummariesIdRouteImport } from './routes/_app/summaries.$id'
import { Route as AppProjectsSettingsRouteImport } from './routes/_app/projects/settings'
import { Route as AppProjectsAddRouteImport } from './routes/_app/projects/add'
import { Route as ApiInstallationsGithubNewRouteImport } from './routes/api/installations/github/new'
import { Route as ApiInstallationsGithubCallbackRouteImport } from './routes/api/installations/github/callback'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/_landing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSummariesIdRoute = AppSummariesIdRouteImport.update({
  id: '/summaries/$id',
  path: '/summaries/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSettingsRoute = AppProjectsSettingsRouteImport.update({
  id: '/projects/settings',
  path: '/projects/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsAddRoute = AppProjectsAddRouteImport.update({
  id: '/projects/add',
  path: '/projects/add',
  getParentRoute: () => AppRoute,
} as any)
const ApiInstallationsGithubNewRoute =
  ApiInstallationsGithubNewRouteImport.update({
    id: '/api/installations/github/new',
    path: '/api/installations/github/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInstallationsGithubCallbackRoute =
  ApiInstallationsGithubCallbackRouteImport.update({
    id: '/api/installations/github/callback',
    path: '/api/installations/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppAppRoute
  '/sign-in': typeof AuthSignInRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/test': typeof ApiTestRoute
  '/': typeof LandingIndexRoute
  '/projects/add': typeof AppProjectsAddRoute
  '/projects/settings': typeof AppProjectsSettingsRoute
  '/summaries/$id': typeof AppSummariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/installations/github/callback': typeof ApiInstallationsGithubCallbackRoute
  '/api/installations/github/new': typeof ApiInstallationsGithubNewRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppAppRoute
  '/sign-in': typeof AuthSignInRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/test': typeof ApiTestRoute
  '/': typeof LandingIndexRoute
  '/projects/add': typeof AppProjectsAddRoute
  '/projects/settings': typeof AppProjectsSettingsRoute
  '/summaries/$id': typeof AppSummariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/installations/github/callback': typeof ApiInstallationsGithubCallbackRoute
  '/api/installations/github/new': typeof ApiInstallationsGithubNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/app': typeof AppAppRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/test': typeof ApiTestRoute
  '/_landing/': typeof LandingIndexRoute
  '/_app/projects/add': typeof AppProjectsAddRoute
  '/_app/projects/settings': typeof AppProjectsSettingsRoute
  '/_app/summaries/$id': typeof AppSummariesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/installations/github/callback': typeof ApiInstallationsGithubCallbackRoute
  '/api/installations/github/new': typeof ApiInstallationsGithubNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/sign-in'
    | '/api/inngest'
    | '/api/test'
    | '/'
    | '/projects/add'
    | '/projects/settings'
    | '/summaries/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/api/installations/github/callback'
    | '/api/installations/github/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/sign-in'
    | '/api/inngest'
    | '/api/test'
    | '/'
    | '/projects/add'
    | '/projects/settings'
    | '/summaries/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/api/installations/github/callback'
    | '/api/installations/github/new'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/app'
    | '/_auth/sign-in'
    | '/api/inngest'
    | '/api/test'
    | '/_landing/'
    | '/_app/projects/add'
    | '/_app/projects/settings'
    | '/_app/summaries/$id'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/webhooks/github'
    | '/api/installations/github/callback'
    | '/api/installations/github/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiTestRoute: typeof ApiTestRoute
  LandingIndexRoute: typeof LandingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiInstallationsGithubCallbackRoute: typeof ApiInstallationsGithubCallbackRoute
  ApiInstallationsGithubNewRoute: typeof ApiInstallationsGithubNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/summaries/$id': {
      id: '/_app/summaries/$id'
      path: '/summaries/$id'
      fullPath: '/summaries/$id'
      preLoaderRoute: typeof AppSummariesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/settings': {
      id: '/_app/projects/settings'
      path: '/projects/settings'
      fullPath: '/projects/settings'
      preLoaderRoute: typeof AppProjectsSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/add': {
      id: '/_app/projects/add'
      path: '/projects/add'
      fullPath: '/projects/add'
      preLoaderRoute: typeof AppProjectsAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/installations/github/new': {
      id: '/api/installations/github/new'
      path: '/api/installations/github/new'
      fullPath: '/api/installations/github/new'
      preLoaderRoute: typeof ApiInstallationsGithubNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/installations/github/callback': {
      id: '/api/installations/github/callback'
      path: '/api/installations/github/callback'
      fullPath: '/api/installations/github/callback'
      preLoaderRoute: typeof ApiInstallationsGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppProjectsAddRoute: typeof AppProjectsAddRoute
  AppProjectsSettingsRoute: typeof AppProjectsSettingsRoute
  AppSummariesIdRoute: typeof AppSummariesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppProjectsAddRoute: AppProjectsAddRoute,
  AppProjectsSettingsRoute: AppProjectsSettingsRoute,
  AppSummariesIdRoute: AppSummariesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiTestRoute: ApiTestRoute,
  LandingIndexRoute: LandingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiInstallationsGithubCallbackRoute: ApiInstallationsGithubCallbackRoute,
  ApiInstallationsGithubNewRoute: ApiInstallationsGithubNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
